# config.yaml

usage_parameters:
  input_video_path: "input/video/path/.mp4"
  output_base_dir: "output/data/dir"
  n_classes: 2
  player_labels: [2, 3]
  ball_labels: [1]
  verbosity: 2  # 0=WARNING, 1=INFO, 2=DEBUG

detection_parameters:
  yolo_model_path: "./models/yolov8-soccer-demo.pt"

homography_parameters:
  input_layout_image: "input/layout/image"
